/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.sekolah;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * 
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    private guru gr=new guru();
    private siswa s=new siswa();
    private pelajaran p=new pelajaran();
    private nilai n=new nilai();
    private ruang r=new ruang();
    private panelUtama pu=new panelUtama();
    private administrasi a=new administrasi();
    private jadwal j=new jadwal();
    private contact c=new contact();
    private help h=new help();
    
    
    
    public FormUtama() {
        setTitle("Sistemasi Sekolah");
        initComponents();
        setLocationRelativeTo(null);
        panel1.add(pu, "panelUtama");
        panel1.add(gr, "guru");
        panel1.add(s, "siswa");
        panel1.add(p, "pelajaran");
        panel1.add(n, "nilai");
        panel1.add(r, "ruang");
        panel1.add(a, "administrasi");
        panel1.add(j, "jadwal");
        panel1.add(c, "contact");
        panel1.add(h, "help");
        setbutton();
    }
    
    void setbutton(){
        button1.setHorizontalTextPosition(SwingConstants.CENTER);
        button1.setVerticalTextPosition(SwingConstants.BOTTOM);
        button2.setHorizontalTextPosition(SwingConstants.CENTER);
        button2.setVerticalTextPosition(SwingConstants.BOTTOM);
        button3.setHorizontalTextPosition(SwingConstants.CENTER);
        button3.setVerticalTextPosition(SwingConstants.BOTTOM);
        button4.setHorizontalTextPosition(SwingConstants.CENTER);
        button4.setVerticalTextPosition(SwingConstants.BOTTOM);
        button5.setHorizontalTextPosition(SwingConstants.CENTER);
        button5.setVerticalTextPosition(SwingConstants.BOTTOM);
        button6.setHorizontalTextPosition(SwingConstants.CENTER);
        button6.setVerticalTextPosition(SwingConstants.BOTTOM);
        button7.setHorizontalTextPosition(SwingConstants.CENTER);
        button7.setVerticalTextPosition(SwingConstants.BOTTOM);
        button8.setHorizontalTextPosition(SwingConstants.CENTER);
        button8.setVerticalTextPosition(SwingConstants.BOTTOM);
        button9.setHorizontalTextPosition(SwingConstants.CENTER);
        button9.setVerticalTextPosition(SwingConstants.BOTTOM);
        button10.setHorizontalTextPosition(SwingConstants.CENTER);
        button10.setVerticalTextPosition(SwingConstants.BOTTOM);
        button11.setHorizontalTextPosition(SwingConstants.CENTER);
        button11.setVerticalTextPosition(SwingConstants.BOTTOM);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new design.background();
        panelTransparant5 = new design.panelTransparant();
        button1 = new design.button();
        button2 = new design.button();
        button3 = new design.button();
        button4 = new design.button();
        button5 = new design.button();
        button6 = new design.button();
        button7 = new design.button();
        button8 = new design.button();
        panelTransparant1 = new design.panelTransparant();
        button9 = new design.button();
        button10 = new design.button();
        button11 = new design.button();
        panel1 = new design.panelTransparant();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTransparant5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        button1.setText("Home");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelTransparant5.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 50));

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guru.png"))); // NOI18N
        button2.setText("Data Guru");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelTransparant5.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 50));

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/siswa.png"))); // NOI18N
        button3.setText("Data Siswa");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panelTransparant5.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 50));

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pelajaran.png"))); // NOI18N
        button4.setText("Data Pelajaran");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        panelTransparant5.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 50));

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administrasi.png"))); // NOI18N
        button5.setText("Administrasi");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        panelTransparant5.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 50));

        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jadwal.png"))); // NOI18N
        button6.setText("Jadwal");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        panelTransparant5.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 110, 50));

        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nilai.png"))); // NOI18N
        button7.setText("Data Nilai");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        panelTransparant5.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, 50));

        button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kelas.png"))); // NOI18N
        button8.setText("Data Ruangan");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        panelTransparant5.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 130, 50));

        background1.add(panelTransparant5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 170, 550));

        panelTransparant1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        button9.setText("Exit");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        panelTransparant1.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 100, 50));

        button10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        button10.setText("Help");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        panelTransparant1.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 100, 50));

        button11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contack.png"))); // NOI18N
        button11.setText("Contact");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        panelTransparant1.add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 100, 50));

        background1.add(panelTransparant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 970, 70));

        panel1.setLayout(new java.awt.CardLayout());
        background1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 13, 785, 550));

        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "guru");
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "panelUtama");
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "siswa");
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "pelajaran");
    }//GEN-LAST:event_button4ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "nilai");
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "ruang");
    }//GEN-LAST:event_button8ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "administrasi");
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "jadwal");
    }//GEN-LAST:event_button6ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        int x =JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin Keluar ?","Anda Yakin ?",JOptionPane.YES_NO_OPTION);
        if (x==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_button9ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "contact");
    }//GEN-LAST:event_button11ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help");
    }//GEN-LAST:event_button10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private design.background background1;
    private design.button button1;
    private design.button button10;
    private design.button button11;
    private design.button button2;
    private design.button button3;
    private design.button button4;
    private design.button button5;
    private design.button button6;
    private design.button button7;
    private design.button button8;
    private design.button button9;
    private design.panelTransparant panel1;
    private design.panelTransparant panelTransparant1;
    private design.panelTransparant panelTransparant5;
    // End of variables declaration//GEN-END:variables
}
