/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.sekolah;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @
 */
public class help extends javax.swing.JPanel {

    /**
     * Creates new form guru
     */
    private help1 h1=new help1();
    private help2 h2=new help2();
    private help3 h3=new help3();
    private help4 h4=new help4();
    private help5 h5=new help5();
    private help6 h6=new help6();
    private help7 h7=new help7();
    private help8 h8=new help8();
    private help9 h9=new help9();
    
    public help() {
        initComponents();
        panel1.add(h1, "help1");
        panel1.add(h2, "help2");
        panel1.add(h3, "help3");
        panel1.add(h4, "help4");
        panel1.add(h5, "help5");
        panel1.add(h6, "help6");
        panel1.add(h7, "help7");
        panel1.add(h8, "help8");
        panel1.add(h9, "help9");
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        background22 = new design.background2();
        panelTransparant1 = new design.panelTransparant();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        panel1 = new design.panelTransparant();
        panelTransparant3 = new design.panelTransparant();

        setMinimumSize(new java.awt.Dimension(657, 501));
        setPreferredSize(new java.awt.Dimension(785, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTransparant1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Data Guru");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        panelTransparant1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Data Siswa");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        panelTransparant1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Data Pelajaran");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        panelTransparant1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Data Nilai");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        panelTransparant1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Data Ruangan");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        panelTransparant1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Administrasi");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        panelTransparant1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Jadwal");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        panelTransparant1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("Contact");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        panelTransparant1.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("Exit");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        panelTransparant1.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        background22.add(panelTransparant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 320));

        panel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelTransparant3Layout = new javax.swing.GroupLayout(panelTransparant3);
        panelTransparant3.setLayout(panelTransparant3Layout);
        panelTransparant3Layout.setHorizontalGroup(
            panelTransparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        panelTransparant3Layout.setVerticalGroup(
            panelTransparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        panel1.add(panelTransparant3, "card2");

        background22.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 510, 330));

        add(background22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help1");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help2");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help3");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help4");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help5");
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help6");
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help7");
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help8");
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        CardLayout cl=(CardLayout)panel1.getLayout();
        cl.show(panel1, "help9");
    }//GEN-LAST:event_jRadioButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private design.background2 background22;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private design.panelTransparant panel1;
    private design.panelTransparant panelTransparant1;
    private design.panelTransparant panelTransparant3;
    // End of variables declaration//GEN-END:variables
}
